FROM eywalker/tensorflow-jupyter:v1.0.1-cuda8.0-cudnn5

RUN pip3 install seaborn
RUN pip3 install --upgrade tensorflow
RUN pip3 install git+https://github.com/datajoint/datajoint-python.git

WORKDIR /src

ADD . /src/Plasticity_Ker/PlasticityKer
RUN pip3 install -e /src/Plasticity_Ker/PlasticityKer
